INDIGO_TITLE_MESSAGE: "iBienvenido(a) a nuestra plataforma donde aprenderás de manera entretenida y multidisciplinaria."
INDIGO_SUBTITLE_MESSAGE: "Acá podrás encontrar llamadas, encuestas, test, videos, textos, libros, imágenes y todo en un lugar, complementando el contenido oficial de nuestra escuela con las plataformas de contenido más aclamadas y probadas del mundo. Comienza aqui el camino hacia la educación del futuro."
INDIGO_PRIMARY_COLOR: "#0F9796" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
    - title: "Indigo theme for Open edX"
      url: "https://github.com/overhangio/indigo"
